using System.Text;

namespace E_learning_platform.Patterns.TemplateMethod
{
    public abstract class ReportGenerator
    {
        // Template Method
        public string GenerateReport()
        {
            var sb = new StringBuilder();
            sb.AppendLine(PrintHeader());
            sb.AppendLine(PrintContent());
            sb.AppendLine(PrintFooter());
            return sb.ToString();
        }

        protected abstract string PrintHeader();
        protected abstract string PrintContent();

        protected virtual string PrintFooter()
        {
            return "----------------------------------\nGenerated by E-learning Platform Automation System";
        }
    }
}
